spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/project_manager;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  banner:
    location: application_banner.txt
server:
  error:
    include-stacktrace: never

application:
  security:
    jwt:
      public_key: classpath:keys/app.pub
      private_key: classpath:keys/app.key