spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/project_manager;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  banner:
    location: application_banner.txt
server:
  error:
    include-stacktrace: never
    include-binding-errors: never